url: https://fab.pm
baseurl: /
title: fab.pm
tagline: Yet another personal blog
description: A personal Jekyll blog hosted on Github Pages
logo: assets/images/favicon/android-chrome-512x512.png
author:
  name: fp555
  url: https://github.com/fp555
timezone: Europe/Rome
date_format: "%-d %B %Y"
permalink: /:year/:y_day

# classic, dark, solarized, solarized-dark
skin: dark

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - pages/blog.html
 
 # Jekyll will ignore these files/paths
exclude: [README.md]

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-gist
 - jekyll-mentions
 - jekyll-redirect-from
 - jekyll-relative-links
 - jemoji

feed:
  path: feed.xml

gist:
  noscript: true

redirect_from:
  json: false

relative_links:
  enabled: true
  collections: true

emoji:
  src: https://github.githubassets.com/images/icons/

# set your GA ID to include analytics
google_analytics: false

# Github Pages defaults
lsi: false
safe: false # changed from true to install non whitelisted plugins
incremental: false
profile: false
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
sass:
  implementation: sass-embedded
  sourcemap: development
 
# Settings for GitHub devcontainer
# livereload not supported by Github environment
port: 4000
livereload: false
